"""add history cache

Revision ID: b9cf25c84638
Revises: 
Create Date: 2024-12-19 14:30:36.861843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9cf25c84638'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('canvas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('history_data', sa.BLOB(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('canvas', schema=None) as batch_op:
        batch_op.drop_column('history_data')

    # ### end Alembic commands ###
